import JSZip from 'jszip';
import { generateShader } from './generator';
import { sanitizedProjectName } from './project';
import type { ProjectV1 } from './types';

const mitLicense = (year: number) =>
  `MIT License\n\nCopyright (c) ${year} DG Matchbox Builder creator\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files, to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.`;
const CC = `Preview image and documentation: Creative Commons Attribution 4.0 International (CC BY 4.0).\nhttps://creativecommons.org/licenses/by/4.0/`;

export async function buildExport(project: ProjectV1, thumbnail?: Blob | null) {
  const generated = generateShader(project);
  const basename = sanitizedProjectName(project.title);
  const zip = new JSZip();
  const options = { date: new Date('1980-01-01T00:00:00.000Z') };
  zip.file(`${basename}.glsl`, generated.flame, options);
  zip.file(`${basename}.xml`, generated.xml, options);
  zip.file(`${basename}.dgmb.json`, JSON.stringify(project, null, 2), options);
  if (thumbnail) zip.file(`${basename}.glsl.png`, thumbnail, options);
  zip.file('README.txt', englishReadme(basename), options);
  zip.file('validate-and-install.command', helperScript(basename), {
    ...options,
    unixPermissions: '755',
  });
  zip.file('validate-and-install.sh', helperScript(basename), {
    ...options,
    unixPermissions: '755',
  });
  zip.file(
    'LICENSE-CODE.txt',
    mitLicense(new Date(project.createdAt).getUTCFullYear() || 2026),
    options,
  );
  zip.file('LICENSE-MEDIA.txt', CC, options);
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
  });
  const digest = await crypto.subtle.digest(
    'SHA-256',
    await blob.arrayBuffer(),
  );
  return {
    blob,
    basename,
    sha256: [...new Uint8Array(digest)]
      .map((byte) => byte.toString(16).padStart(2, '0'))
      .join(''),
    files: Object.keys(zip.files),
  };
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

const englishReadme = (name: string) =>
  `Matchbox generated by DG Matchbox Builder.\n\n1. Keep ${name}.glsl and ${name}.xml in the same folder.\n2. Run validate-and-install.command on macOS or validate-and-install.sh on Linux from a Flame workstation.\n3. The helper validates first and asks before installing. It never silently overwrites an existing shader.\n\nTarget: Flame 2025.1+ / Reference: Flame 2025.2.7\nThe browser preview is an approximation. Always confirm the final image in Flame.`;
const helperScript = (name: string) => `#!/bin/sh
set -eu
BASE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SHADER="$BASE_DIR/${name}.glsl"
find_builder() {
  if command -v shader_builder >/dev/null 2>&1; then command -v shader_builder; return; fi
  for candidate in /opt/Autodesk/*/bin/shader_builder /Applications/Autodesk/*/bin/shader_builder; do
    if [ -x "$candidate" ]; then printf '%s\\n' "$candidate"; return; fi
  done
  return 1
}
BUILDER=$(find_builder || true)
if [ -z "$BUILDER" ]; then printf '%s\\n' "shader_builder was not found. Run this on a Flame workstation."; exit 1; fi
BUILD_DIR=$(mktemp -d "${name}.XXXXXX")
trap 'rm -rf "$BUILD_DIR"' EXIT INT TERM
"$BUILDER" -m -x -o "$BUILD_DIR" "$SHADER"
printf '%s\\n' "Validation passed. Generated files are in: $BUILD_DIR"
printf '%s' "Create an encrypted .mx package too? [y/N] "
read answer
case "$answer" in y|Y) "$BUILDER" -m -p -o "$BUILD_DIR" "$SHADER" ;; esac
printf '%s' "Install the validated files? Enter destination folder, or press Return to stop: "
read destination
[ -n "$destination" ] || exit 0
mkdir -p "$destination"
for source in "$BUILD_DIR"/*; do
  target="$destination/$(basename "$source")"
  if [ -e "$target" ]; then printf '%s\\n' "Skipped existing file: $target"; else cp "$source" "$target"; fi
done
printf '%s\\n' "Installation complete. Restart or rescan Matchbox in Flame."
`;
